language: python

cache: pip

python:
    - "3.6-dev"
    - "3.7-dev"
    - "3.8-dev"

install:
    - pip install poetry
    - poetry install

script:
    - poetry run nosetests-3.4 --with-coverage --cover-package=pymispwarninglists -d

after_success:
    - codecov
    - coveralls
