language: python

cache: pip

python:
    - "3.6-dev"
    - "3.7-dev"

install:
    - pipenv install -d .

script:
    - pipenv run nosetests-3.4 --with-coverage --cover-package=pymispwarninglists -d

after_success:
    - codecov
    - coveralls
