name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}

    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install -E fetch_lists

    - name: Test with nosetests
      run: |
        poetry run pytest --cov=pymispwarninglists tests/tests.py
        poetry run mypy .

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
